group:
  lampor1:
    name: Lampor1
    view: true
    icon: mdi:lightbulb
    entities:
      - group.telldusLights
      - group.ikeaKronLjus
      - group.kokMatbord

  telldusLights:
    name: LampGrupp1
    view: false
    entities:
      - switch.TD06
      - switch.TD07
      - switch.TD08

  kokMatbord:
    name: Kok mat
    view: false
    entities:
      - light.kok1
      - light.kok2
  
  ikeaKronLjus:
    name: LampGrupp2
    view: false
    entities:
      - light.kron1


automation:
  - alias: Turn on at sun sets
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-01:00:00"
    action:
      service: switch.turn_on
      entity_id: group.telldusLights

  - alias: Turn off when sun rise
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunrise
      offset: "01:00:00"
    action:
      service: switch.turn_off
      entity_id: group.telldusLights

  - alias: Turn off the lights at evening
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      at: "23:00:00"
    action:
      - service: switch.turn_off
        entity_id: group.telldusLights
      - service: light.turn_on
        data:
          brightness: 10
          entity_id: light.kron1

